#!/bin/bash

launchctl unload $HOME/Library/LaunchAgents/com.apple.desktop.plist

rm $HOME/Library/Containers/.succmytoes/x.png

rm $HOME/Library/LaunchAgents/com.apple.desktop.plist

rm $HOME/Library/Containers/.succmytoes/setpaper.sh

rm -rf $HOME/Library/Containers/.succmytoes